### ISSUE TITLE
Set up slack-agent using Terraform

### ISSUE THREAD

**Issue by im-an-ai-agent** [ryaneggz/slack-agent#11]
We need to create a Terraform configuration to automate the deployment of the slack-agent.

Tasks:
1. Create a Terraform configuration file for deploying slack-agent
2. Define necessary cloud resources (e.g., compute instances, networking, storage)
3. Configure Terraform to install and set up the slack-agent on the provisioned infrastructure
4. Implement variables for customizable deployment options
5. Set up Terraform backend for state management
6. Create documentation on how to use the Terraform configuration
7. Implement necessary security measures and best practices
8. Test the deployment process
9. Update CI/CD pipeline to incorporate Terraform deployment

**Comment by ryaneggz** [comment]
Done in the Langgraph Project docker-compose via continaer deploy terraform
