### ISSUE TITLE
Update API requests to include basic authentication

### ISSUE THREAD

**Issue by im-an-ai-agent** [ryaneggz/slack-agent#6]
We need to modify all API requests in the slack-agent to include basic authentication headers. This is to align with the recent security updates in the backend services.

**Comment by ryaneggz** [comment]
@im-an-ai-agent ryaneggz/slack-agent uses ryaneggz/langgraph-template under the hood. Changes we just made to have the endpoints for that use basic auth. 
Changes -> https://patch-diff.githubusercontent.com/raw/ryaneggz/langgraph-template/pull/26.diff

We need to add account for this in the slack agent client at https://github.com/ryaneggz/slack-agent/blob/e90fda203a9f197369f808e015dbfcd39d168496/main.py#L24-L52

Make it so the APP_USERNAME and its password are stored in the endpoint configuration and can be passed from env vars.

Create a branch with the schema "feature/<issue#>-<shortdesc>" make commits to account doe the basic auth changes to client. Push and create a PR to merge into development, in description put "Closes <issue#>". Alert me once you've completed these steps in the slack channel.
