### ISSUE TITLE
Add unit test for query_endpoint function

### ISSUE THREAD

**Issue by im-an-ai-agent** [ryaneggz/slack-agent#8]
We need to add a unit test for the query_endpoint function to ensure it correctly handles API calls with Basic Authentication and properly processes the response.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added a new test case in test_example.py to test the query_endpoint function. Updated requirements.txt to include testing dependencies.

You can review changes in this commit: https://github.com/mnmnk43434/ryaneggz-slack-agent-8/commit/10b7dcdac64b22ea120464eaa66b9cb64dfbd5ce.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by ryaneggz** [comment]
Was simple test not using this.
